---
collections:
  - name: community.mongodb
  - name: dtvlinux.cis_hardening

roles:
  - name: buluma.os_updates
    # Latest stable version is pulled automatically.
    # You can pin it: version: "1.7.0"
    #3408173fe9d1c0c2692abd8f4ee233c10ce6e33c