---
collections:
  - name: community.mongodb
  - name: dtvlinux.cis_hardening

roles:
  - name: buluma.os_updates
    # Latest stable version is pulled automatically.
    # You can pin it: version: "1.7.0"