#cloud-config
users:
  - name: ubuntu
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
ssh_pwauth: True
chpasswd:
  list: |
    ubuntu:ubuntu ## Overriding default username, password
  expire: True