[kali_vm]
kali-VM ansible_host=192.168.1.115 ansible_user=kali

[Apache-Airflow-VM]
Apache-Airflow-VM ansible_host=100.65.206.42 ansible_user=root
rebuilt-airflow-VM ansible_host=192.168.1.170 ansible_user=admin

[oracle-linux-VM]
Atlassian-VM ansible_host=192.168.1.192 ansible_user=root

[postgresql-VM]
postgresql-VM ansible_host=192.168.1.155 ansible_user=admin

[awx-ubuntu-vm]
ubuntu-awx-vm ansible_host=192.168.1.186 ansible_user=devops

[redhat-vms]
airflowvm1 ansible_host=192.168.1.146 ansible_user=root

[ubuntu-vms]
ubuntuvm1 ansible_host=192.168.1.186 ansible_user=devops
ubuntuvm2 ansible_host=192.168.1.187 ansible_user=devops
ubuntuvm3 ansible_host=192.168.1.188 ansible_user=devops
ubuntuvm4 ansible_host=192.168.1.126 ansible_user=devops

#AWX-vm ansible_host=100.85.48.73 ansible_user=devops

#galaxy token=2a89a665191f9c1066344a1fba5db8907f6401aa