---
- name: Setup Docker on Hosts
  hosts: ubuntuvm3
  become: true
  
  tasks:
    - name: Disable CD-ROM repository to fix apt update errors
      replace:
        path: /etc/apt/sources.list
        regexp: '^(deb cdrom:.*)'
        replace: '# \1'

    - name: Import geerlingguy.docker role
      include_role:
        name: geerlingguy.docker