#system update using robertdebock.update
---
- name: Update System Packages
  hosts: all
  become: true
  tasks:

    - name: Comment out CD-ROM repositories in sources.list
      replace:
        path: /etc/apt/sources.list
        regexp: '^(deb cdrom:.*)'
        line: '# \1'
      become: yes

    - name: Update system packages
      include_role:
        name: robertdebock.update
      vars:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes
        purge: yes
